(function(jwplayer){var minPlayerVersion='7.0',pluginName='danmu',pluginVersion='0.2.1a';var _T=function(s){return jwplayer._T(s,_);},_={eng:{_icon:'💬',danmu_is_empty:'Your danmu is empty...',danmu_too_intense:'Your post is so intense. How about having a break?',danmu_too_long:'Your danmu is too long...',not_connected_to_danmu_server:'You have not connected to danmu server yet...',type_danmu_and_press_enter:'Type your danmu here and press Enter to submit.'},cht:{_icon:'彈',danmu_is_empty:'彈幕內容為空...',danmu_too_intense:'發言頻率過高...',danmu_too_long:'彈幕內容過長...',not_connected_to_danmu_server:'尚未與彈幕伺服器連線...',type_danmu_and_press_enter:'想要發射點彈幕嗎 (ﾉ≧ڡ≦)'},chs:{_icon:'弹',danmu_is_empty:'弹幕内容为空...',danmu_too_intense:'发言频率过高...',danmu_too_long:'弹幕内容过长...',not_connected_to_danmu_server:'尚未与弹幕服务器连接...',type_danmu_and_press_enter:'想要发射点弹幕么 (ﾉ≧ڡ≦)'}};var template=function(player,config,div){var container,video;var danmuBox,danmuForm,danmuInput,danmuOnline,danmuCount,danmuTextLength;var defaultEnable=false,dataPackMethod='Json',socketAddr='127.0.0.1:2346',socketSsl=false,maxLength=50,globalScale=1,scrollScale=1,minPostInterval=5*1000,maxPausePeriod=300*1000,pingInterval=60*1000;var isSocketInit=true,currentEnable=defaultEnable,shouldShowDanmu=defaultEnable,lastpost=0,pingPongTimer=-1,cid,pauseIdleTimer;var referer=typeof CANONICAL_URL!='undefined'?CANONICAL_URL:document.location.href;var SOCKET_READYSTATE_OPEN=1,SOCKET_READYSTATE_CLOSED=3;window.socket={readyState:SOCKET_READYSTATE_CLOSED};config.defaultEnable!==undefined?defaultEnable=!!config.defaultEnable:'';config.dataPackMethod!==undefined?dataPackMethod=String(config.dataPackMethod):'';config.socketAddr!==undefined?socketAddr=String(config.socketAddr):'';config.socketSsl!==undefined?socketSsl=!!config.socketSsl:'';config.maxLength!==undefined?maxLength=parseInt(config.maxLength,10):'';config.globalScale!==undefined?globalScale=parseFloat(config.globalScale):'';config.scrollScale!==undefined?scrollScale=parseFloat(config.scrollScale):'';config.minPostInterval!==undefined?minPostInterval=parseInt(config.minPostInterval,10):'';config.maxPausePeriod!==undefined?maxPausePeriod=parseInt(config.maxPausePeriod,10):'';config.pingInterval!==undefined?pingInterval=parseInt(config.pingInterval,10):'';jwplayer.getCookie('danmuEnable')!==''?defaultEnable=+jwplayer.getCookie('danmuEnable'):'';player.on('ready',function(){container=document.querySelector('#'+player.id);video=container.querySelector('video');addMenu();addMenuFunction();prepareDanmuContainer();addDanmuFormFunction();addDanmuInputFunction();initDanmu();setupPlayerListener();setPluginEnable(defaultEnable);});function addMenu(){var html='<div class="jw-icon jw-icon-tooltip jw-icon-'+pluginName+' jw-reset jw-toggle"></div>';container.querySelector('.jw-text-duration').insertAdjacentHTML('afterend',html);}
function addMenuFunction(){var menu=container.querySelector('.jw-icon-tooltip.jw-icon-'+pluginName);menu.addEventListener('click',toggleEnable);menu.addEventListener('touchstart',toggleEnable);function toggleEnable(){jwplayer.setCookie('danmuEnable',+!currentEnable);setPluginEnable(!currentEnable);}}
function setupPlayerListener(){player.on('play',function(){if(!shouldShowDanmu){return;}
cm.start();clearTimeout(pauseIdleTimer);});player.on('pause',function(){if(!shouldShowDanmu){return;}
cm.stop();pauseIdleTimer=setTimeout(function(){if(socket.readyState!==SOCKET_READYSTATE_CLOSED){socket.close();}},maxPausePeriod);});player.on('complete',function(){if(socket.readyState!==SOCKET_READYSTATE_CLOSED){socket.close();}});player.on('time',function(e){if(!shouldShowDanmu){return;}
cm.time(getTimeFromPlayerToDanmu(e.position));});player.on('resize',function(p){cm.width=p.width;cm.height=p.height;});}
function prepareDanmuContainer(){container.classList.add('abp');container.insertAdjacentHTML('afterbegin','<div class="danmu-box">'+'<div class="danmu-form">'+'<div class="danmu-label danmu-label-f-l danmu-online noselect"></div>'+'<div class="danmu-label danmu-label-f-l danmu-count noselect"></div>'+'<div class="danmu-label danmu-label-f-r danmu-text-length noselect"></div>'+'<input class="danmu-label danmu-input" type="text" />'+'</div>'+'</div>'+'<div class="container"></div>');danmuBox=container.querySelector('.danmu-box');danmuForm=danmuBox.querySelector('.danmu-form');danmuInput=danmuForm.querySelector('.danmu-input');danmuOnline=danmuForm.querySelector('.danmu-online');danmuCount=danmuForm.querySelector('.danmu-count');danmuTextLength=danmuForm.querySelector('.danmu-text-length');}
function addDanmuFormFunction(){danmuForm.addEventListener('mouseenter',showForm);danmuForm.addEventListener('mouseleave',hideForm);function showForm(){danmuFormShown=true;danmuForm.style.opacity=1;danmuInput.focus();updateDanmuTextLength();}
function hideForm(){danmuFormShown=false;danmuForm.style.opacity=0;container.focus();}}
function addDanmuInputFunction(){danmuInput.addEventListener('click',function(e){danmuInput.focus();});danmuInput.addEventListener('keyup',updateDanmuTextLength);danmuInput.addEventListener('keydown',function(e){var k=e.which||e.keyCode;if(k==13){if(socket.readyState===SOCKET_READYSTATE_OPEN){if(getTimestamp()- lastpost<minPostInterval){showMessage('error',_T('danmu_too_intense'));}else{var sent=sendDanmu({mode:1,text:danmuInput.value,stime:getTimeFromPlayerToDanmu(),size:25,color:0xFFFFFF},'add');if(sent){updateLastpost();danmuInput.value='';}}}else{initSocket();}}
else if(k==27){danmuForm.style.opacity=0;container.focus();}
e.stopPropagation();});}
function initSocket(){socket=new WebSocket(socketSsl?'wss://'+ socketAddr.replace(/:[0-9]+/,''):'ws://'+ socketAddr);socket.onopen=function(e){console.log('[JW Player] [Danmu] Socket open.',e);console.log('[JW Player] [Danmu] Socket package format:',dataPackMethod);if(dataPackMethod=='Msgpack'){socket.binaryType='arraybuffer';}else{socket.binaryType='blob';}
setPluginEnable(true);danmuInput.placeholder=_T('type_danmu_and_press_enter');danmuInput.classList.remove('error');pingPongTimer=setInterval(pingSocket,pingInterval);socket.send_({act:'registerWatching',cid:cid,referer:referer});if(isSocketInit){isSocketInit=false;socket.send_({act:'loadDanmu'});}};socket.onmessage=function(e){try{var data=socket.unpackData(e.data);}catch(_){console.log(_);console.log('[JW Player] [Danmu] fail unpacking data from server:'+ e.data);return;}
console.log('Client receives data (unpacked):',data);switch(data.act){case'consoleLog':showMessage('note',_T(data.data));break;case'error':showMessage('error',_T(data.data));break;case'add':cm.insert(data.data);break;case'addLive':cm.send(data.data);break;case'loadDanmu':cm.load(data.data);break;case'online_count':danmuOnline.textContent=data.data;break;case'online_count_global':break;case'setMaxLength':maxLength=data.data;break;default:console.log('Unknown act:',data.act);break;}
updateDanmuCount();};socket.onclose=function(e){console.log('[JW Player] [Danmu] Socket closed.',e);setPluginEnable(false,true);danmuInput.placeholder=_T('not_connected_to_danmu_server');danmuInput.classList.add('error');clearInterval(pingPongTimer);};socket.onerror=function(e){console.log('[JW Player] [Danmu] Socket error.',e);setPluginEnable(false,true);danmuInput.placeholder=_T('not_connected_to_danmu_server');danmuInput.classList.add('error');clearInterval(pingPongTimer);};socket.send_=function(data){socket.send(socket.packData(data));};socket.packData=function(data){if(dataPackMethod=='Msgpack'){return msgpack.encode(data);}else{return JSON.stringify(data);}};socket.unpackData=function(data){if(dataPackMethod=='Msgpack'){return msgpack.decode(data);}else{return JSON.parse(data);}};}
function initDanmu(){cid=player.getPlaylistItem()['cid'];cid===undefined?cid='unknown':'';window.cm=new CommentManager(container.querySelector('.container'));cm.options.global.scale=globalScale;cm.options.scroll.scale=scrollScale;cm.init();cm.clear();}
function pingSocket(){try{socket.send_({act:'ping'});}catch(e){}}
function sendDanmu(danmuObj,act){if(act===undefined){return false;}
danmuObj.text=danmuObj.text.replace(/^[\s　]+|[\s　]+$/g,'');if(danmuObj.text===''){showMessage('note',_T('danmu_is_empty'));return false;}
if(danmuObj.text.length>maxLength){showMessage('error',_T('danmu_too_long'));return false;}
socket.send_({act:act,data:danmuObj});switch(act){case'add':case'addLive':danmuObj.border=true;cm.send(danmuObj);if(act=='add'){danmuObj.stime=getTimeFromPlayerToDanmu()- 1;cm.insert(danmuObj);}
break;default:return false;}
updateDanmuCount();return true;}
function setPluginEnable(enable,dueToDisconnected){dueToDisconnected=dueToDisconnected===undefined?false:dueToDisconnected;var menu=container.querySelector('.jw-icon-tooltip.jw-icon-'+pluginName);if(enable){danmuBox.style.display='block';menu.classList.remove('jw-off');currentEnable=true;shouldShowDanmu=true;if(player.getState()=='playing'){cm.start();}
if(socket.readyState!==SOCKET_READYSTATE_OPEN){initSocket();}}else{danmuBox.style.display='none';menu.classList.add('jw-off');currentEnable=false;if(dueToDisconnected){shouldShowDanmu=true;}else{shouldShowDanmu=false;cm.stop();cm.clear();}}}
function getTimeFromPlayerToDanmu(t){t=t||player.getPosition();return Math.round(t*1000);}
function updateLastpost(){lastpost=getTimestamp();}
function updateDanmuCount(){danmuCount.textContent=cm.timeline.length;}
function updateDanmuTextLength(){var length=danmuInput.value.length;danmuTextLength.textContent=length+' / '+ maxLength;if(length>maxLength){danmuTextLength.classList.add('error');}else{danmuTextLength.classList.remove('error');}}
function getTimestamp(){return new Date().getTime();}
function showMessage(type,msg){switch(type){case'note':console.log(msg);break;case'error':alert(msg);break;default:console.log('[???] '+ msg);break;}}};addCss();jwplayer().registerPlugin(pluginName,minPlayerVersion,template);console.log('[JW Player] Plugin loaded: '+pluginName+' v'+pluginVersion);function addCss(){var css='<style type="text/css">';css+='.jw-icon-'+pluginName+':before { content: "'+_T('_icon')+'"; }';css+='.abp .container { pointer-events: none; width: 100%; height: 100%; position: absolute; top: 0; left: 0; }';css+='.abp .container .cmt { font-family: SimHei, Heiti, "Meiryo", "Microsoft JhengHei", "Microsoft YaHei", monospace; font-weight: bold; text-shadow: 0 0 2px #000, -1px 0 #000, 0 1px #000, 1px 0 #000, 0 -1px #000; }';css+='.danmu-box { pointer-events: none; width: 100%; height: 100%; position: absolute; left: 0; right: 0; bottom: 0; z-index: 10002; }';css+='.danmu-box *:before { margin: 0 5px 0 0; }';css+='.danmu-form { pointer-events: auto; margin: 0 auto; width: 400px; max-width: 80%; position: absolute; left: 0; right: 0; bottom: 20%; opacity: 0; transition: opacity .3s ease; }';css+='.danmu-label { padding: 2px 4px; display: inline-block; font-size: 14px; box-sizing: border-box; border: 0; outline: 0; box-shadow: 0 0 15px rgba(0,0,0,.2); border-radius: .3em; }';css+='.danmu-label.error { background: rgba(255,102,102,.7); }';css+='.danmu-label-f-l { float: left; margin: 5px 5px 5px 0; }';css+='.danmu-label-f-r { float: right; margin: 5px 0 5px 5px; }';css+='.danmu-online, .danmu-count { background: rgba(255,255,0,.7); }';css+='.danmu-online:before { content: "👨"; }';css+='.danmu-count:before { content: "💬"; }';css+='.danmu-text-length { background: rgba(255,255,255,.7); }';css+='.danmu-input { font-size: 16px; width: 100%; padding: 6px 8px; margin: 0; background: rgba(255,255,255,.75); }';css+='.jw-title { z-index: 10002; }';css+='.jw-controls .jw-controls-right, .jw-controls .jw-controlbar { z-index: 10002; }';css+='.noselect { user-select: none; cursor: default; }';css+='</style>';document.querySelector('head').insertAdjacentHTML('beforeend',css);}})(jwplayer);